language: csharp
solution: MonitorInternetConnectionApplication.sln
install:
  - nuget restore MonitorInternetConnectionApplication.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release MonitorInternetConnectionApplication.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./MonitorInternetConnectionUnitTests/bin/Release/MonitorInternetConnectionUnitTests.dll
